version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: 
      name: python/default
      tag: '3.7'
    steps:
      -checkout
      - run: 
          name: Setup Virtual Env
          command: |
            virtualenv -p python3.7 env
            source ./env/bin/activate
  